jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
      - run:
          command: |
            pytest --version
          name: Test
orbs:
  python: circleci/python@1.2.0
version: 2.1
workflows:
  main:
    jobs:
      - build