orbs:
  python: circleci/python@1.2.0
version: 2.1
workflows:
  main:
    jobs:
      - python/test:
          args: '.[dev,test]'
          pkg-manager: pip-dist
          test-tool: pytest
      - publish